### rescuperar todas las peliculas
GET http://localhost:1234/movies

### recuperar pelicula por su id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### recuperar por genero
GET http://localhost:1234/movies?genre=cRiMe

### crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1990,
  "director": "Francis Ford Coppola",
  "duration": 500,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### actualizar pelicula
PATCH  http://localhost:1234/movies/7e0b1395-47e1-4919-8ca2-06b23a0ea997
Content-Type: application/json

{
    "title": "Title edited",
    "year": 1993
}

### eliminar pelicula
DELETE http://localhost:1234/movies/f70959c1-c3fb-4ed7-a950-9c60a27c33c9